### ISSUE TITLE
What is missing from my fork?

### ISSUE THREAD

**Issue by jacen92** [LajaSoft/audio-webui-docker#5]
Hi,

I notice you clone my fork instead of the official one, what is missing?
I just need to understand, nothing wrong.
Perhaps we could complete it if needed.

Thanks
+

**Comment by zba** [comment]
Ah I just not get I got a fork, really sorry. The story is short, while i tried to run auidio-webui I found that there is installer.zip :) which makes git clone,  but I didn't know this and wrapped it to docker, so when I run I found it works, so left as is, but I not got that I downloading fork :) I will check now what to do :)
upd: this all wrong, strange more

**Comment by zba** [comment]
sorry, what about clone ? I made it myself,  in my docker there is  
 ```
 RUN wget https://github.com/gitmylo/audio-webui/releases/download/Installers/audio-webui.zip
 ```
(inside it git clone https://github.com/gitmylo/audio-webui)
 which is official as i understand I though I cloned your because I found commit in main repo. so now i not sure if need any actions or thoughs :)

**Comment by zba** [comment]
Oh I got it I just add wrong url to readme :) was sleepy
